const assert = require('node:assert/strict');
const { SqliteStore } = require('../host/store/sqlite-store');
const { ApprovalService } = require('../host/approvals/service');
const { WorkflowService } = require('../host/workflows/service');
const { FollowUpWorkflow } = require('../host/workflows/follow-up');

const store = new SqliteStore();
const approvals = new ApprovalService({ store });
const workflows = new WorkflowService({ store });
const followUp = new FollowUpWorkflow({ store, approvals, workflows });
store.saveTaskCandidate({ candidateId: 'task-1', observationId: 'obs-1', summary: 'Handoff', counterparty: 'alex@example.com', threadId: 'thread-1', evidence: { start: 0, end: 1, text: 'Handoff' }, extractorVersion: 'test' });
const result = followUp.prepare({ taskId: 'task-1', status: 'active', summary: 'Handoff', counterparty: 'alex@example.com', threadId: 'thread-1', updatedAt: 42 }, { body: 'Checking on the handoff.' });
assert.equal(result.workflow.state, 'awaiting_approval');
assert.equal(result.approval.action.capability, 'gmail.send');
assert.equal(result.approval.action.workflowId, result.workflow.workflowId);
assert.equal(result.workflow.payload.requestId, result.approval.request_id || result.approval.requestId);
store.saveTaskCandidate({ candidateId: 'task-approval-stale', observationId: 'obs-approval-stale', summary: 'Approval stale', counterparty: 'alex@example.com', threadId: 'thread-approval-stale', evidence: { start: 0, end: 1, text: 'Review' }, extractorVersion: 'test' });
const pendingFollowUp = followUp.prepare({ taskId: 'task-approval-stale', status: 'active', summary: 'Approval stale', counterparty: 'alex@example.com', threadId: 'thread-approval-stale' }, { body: 'Please review.' });
const staleRequestId = pendingFollowUp.workflow.payload.requestId;
store.correctTask('task-approval-stale', { summary: 'Corrected approval obligation' });
assert.equal(store.getApproval(staleRequestId).status, 'cancelled', 'task corrections cancel pending approvals');
assert.equal(store.getWorkflow(pendingFollowUp.workflow.workflowId).state, 'needs_attention', 'task corrections stop awaiting-approval workflows');
const invalidated = followUp.observeReplies([{ observationId: 'newer-than-draft', threadId: 'thread-approval-stale', direction: 'incoming', timestamp: Date.now() + 1, body: 'Already handled.' }]);
assert.equal(invalidated.length, 0, 'already-invalidated workflows are not reprocessed');
assert.equal(store.getApproval(staleRequestId).status, 'cancelled');
store.saveObservation({ observationId: 'obs-source-removal', messageId: 'msg-source-removal', threadId: 'thread-source-removal', subject: 'Review', body: 'Please review.', direction: 'incoming' }, 'gmail:source-removal');
store.saveTaskCandidate({ candidateId: 'task-source-removal', observationId: 'obs-source-removal', summary: 'Review source', counterparty: 'alex@example.com', threadId: 'thread-source-removal', evidence: { start: 0, end: 7, text: 'Review' }, extractorVersion: 'test' });
const sourceTask = store.listTasks({ includeDismissed: true }).find((task) => task.taskId === 'task-source-removal');
const sourceFollowUp = followUp.prepare(sourceTask, { body: 'Checking the source task.' });
store.removeObservation('gmail:source-removal', 'msg-source-removal');
assert.equal(store.getApproval(sourceFollowUp.workflow.payload.requestId).status, 'cancelled', 'source deletion cancels pending approvals');
assert.equal(store.getWorkflow(sourceFollowUp.workflow.workflowId).state, 'needs_attention', 'source deletion stops awaiting-approval workflows');
store.updateWorkflow(result.workflow.workflowId, { state: 'waiting_event', payload: { ...result.workflow.payload, threadId: 'thread-1', sentAt: Date.parse('2026-09-17T10:00:00Z') } });
const verifying = followUp.observeReplies([
  { observationId: 'old-reply', threadId: 'thread-1', direction: 'incoming', timestamp: '2026-09-17T09:59:00Z', body: 'An older message.' },
  { observationId: 'reply-1', threadId: 'thread-1', direction: 'incoming', timestamp: '2026-09-17T10:01:00Z', body: 'The handoff is ready.' },
]);
assert.equal(verifying[0].state, 'verifying');
assert.equal(verifying[0].payload.responseObservationId, 'reply-1');
assert.equal(followUp.observeReplies([{ observationId: 'old-only', threadId: 'thread-1', direction: 'incoming', timestamp: '2026-09-17T09:59:30Z', body: 'Still old.' }]).length, 0);
const completed = followUp.reconcileReply(result.workflow.workflowId, { resolved: true, reason: 'reply-confirmed' });
assert.equal(completed.state, 'completed');
assert.equal(store.listTasks({ includeDismissed: true }).find((task) => task.taskId === 'task-1').status, 'done');
store.saveTaskCandidate({ candidateId: 'task-2', observationId: 'obs-2', summary: 'Review', counterparty: 'alex@example.com', threadId: 'thread-2', evidence: { start: 0, end: 1, text: 'Review' }, extractorVersion: 'test' });
const uncertainWorkflow = followUp.prepare({ taskId: 'task-2', status: 'active', summary: 'Review', counterparty: 'alex@example.com', threadId: 'thread-2' }, { body: 'Checking on the review.' });
store.updateWorkflow(uncertainWorkflow.workflow.workflowId, { state: 'waiting_event', payload: { ...uncertainWorkflow.workflow.payload, sentAt: 1000 } });
followUp.observeReplies([{ observationId: 'reply-2', threadId: 'thread-2', direction: 'incoming', timestamp: 1100, body: 'I will look tomorrow.' }]);
assert.equal(followUp.reconcileReply(uncertainWorkflow.workflow.workflowId, { resolved: false, reason: 'reply-needs-user-confirmation' }).state, 'needs_attention');
store.saveTaskCandidate({ candidateId: 'task-no-sent-at', observationId: 'obs-no-sent-at', summary: 'No send timestamp', counterparty: 'alex@example.com', threadId: 'thread-no-sent-at', evidence: { start: 0, end: 1, text: 'Review' }, extractorVersion: 'test' });
const noSentAt = followUp.prepare({ taskId: 'task-no-sent-at', status: 'active', summary: 'No send timestamp', counterparty: 'alex@example.com', threadId: 'thread-no-sent-at' }, { body: 'Checking.' });
store.updateWorkflow(noSentAt.workflow.workflowId, { state: 'waiting_event', payload: { ...noSentAt.workflow.payload } });
assert.equal(followUp.observeReplies([{ observationId: 'old-no-sent-at', threadId: 'thread-no-sent-at', direction: 'incoming', timestamp: noSentAt.workflow.createdAt - 1, body: 'Old reply.' }]).length, 0);
assert.equal(followUp.observeReplies([{ observationId: 'fresh-no-sent-at', threadId: 'thread-no-sent-at', direction: 'incoming', timestamp: noSentAt.workflow.createdAt + 1, body: 'Fresh reply.' }])[0].state, 'verifying');
assert.throws(() => followUp.prepare({ taskId: 'task-2', status: 'done', counterparty: 'alex@example.com', threadId: 'thread-2' }, { body: 'No' }), /active tasks/);
assert.throws(() => followUp.cancel(result.workflow.workflowId), /already completed/);
assert.equal(store.getWorkflow(result.workflow.workflowId).state, 'completed');
store.close();
console.log('follow-up workflow tests passed');
