const assert = require('node:assert/strict');
const { SqliteStore } = require('../host/store/sqlite-store');
const { JobRunner } = require('../host/workflows/job-runner');

let now = 1000;
const store = new SqliteStore({ clock: () => now });
const first = store.enqueueJob({ kind: 'test', payload: { value: 1 }, dedupeKey: 'same' });
const duplicate = store.enqueueJob({ kind: 'test', payload: { value: 2 }, dedupeKey: 'same' });
assert.equal(duplicate.deduplicated, true);
assert.equal(store.claimJobs({ workerId: 'worker', now }).length, 1);
const claimed = store.getJob(first.jobId);
assert.equal(claimed.attempts, 1);
assert.equal(store.renewJob(first.jobId, claimed.leaseToken, 120_000, now), true);
assert.equal(store.getJob(first.jobId).leaseUntil, now + 120_000);
assert.throws(() => store.completeJob(first.jobId, 'wrong', { status: 'completed' }), /lease/);

(async () => {
  const runner = new JobRunner({ store, workerId: 'runner', clock: () => now });
  runner.register('test', async (payload) => { assert.equal(payload.value, 1); });
  // Reclaim the lease after its deadline to exercise restart recovery.
  now += 121_000;
  const results = await runner.runOnce();
  assert.equal(results[0].status, 'completed');
  assert.equal(store.getJob(first.jobId).status, 'completed');
  const retry = store.enqueueJob({ kind: 'missing', payload: {}, maxAttempts: 1 });
  const failed = await runner.runOnce();
  assert.equal(failed[0].jobId, retry.jobId);
  assert.equal(store.getJob(retry.jobId).status, 'failed');
  assert.ok(store.exportData().data.jobs.length >= 2);
  const slowStore = new SqliteStore();
  const slowJob = slowStore.enqueueJob({ kind: 'slow', payload: {}, maxAttempts: 1 });
  const slowRunner = new JobRunner({ store: slowStore, workerId: 'slow-runner', leaseMs: 30 });
  slowRunner.register('slow', async () => new Promise((resolve) => setTimeout(resolve, 80)));
  const slowResult = await slowRunner.runOnce();
  assert.equal(slowResult[0].status, 'completed');
  assert.equal(slowStore.getJob(slowJob.jobId).status, 'completed');
  slowStore.close();
  let fencedNow = 1000;
  const fencedStore = new SqliteStore({ clock: () => fencedNow });
  const fencedJob = fencedStore.enqueueJob({ kind: 'fenced', payload: {}, maxAttempts: 2 });
  let releaseFenced;
  const firstRunner = new JobRunner({ store: fencedStore, workerId: 'first-owner', leaseMs: 50, clock: () => fencedNow });
  firstRunner.register('fenced', async () => new Promise((resolve) => { releaseFenced = resolve; }));
  const firstRun = firstRunner.runOnce();
  await new Promise((resolve) => setImmediate(resolve));
  fencedNow = 2000;
  const secondRunner = new JobRunner({ store: fencedStore, workerId: 'replacement-owner', leaseMs: 50, clock: () => fencedNow });
  let replacementRuns = 0;
  secondRunner.register('fenced', async () => { replacementRuns += 1; });
  const replacement = await secondRunner.runOnce();
  assert.equal(replacementRuns, 1);
  assert.equal(replacement[0].status, 'completed');
  releaseFenced();
  const stale = await firstRun;
  assert.equal(stale[0].leaseLost, true);
  assert.equal(fencedStore.getJob(fencedJob.jobId).status, 'completed');
  fencedStore.close();
  store.close();
  console.log('job tests passed');
})().catch((error) => { console.error(error); process.exitCode = 1; });
