const assert = require('node:assert/strict');
const { MobileCoreClient, NOTIFICATION_CURSOR_KEY, assistantHealthStatus } = require('../mobile/src/client');

assert.equal(assistantHealthStatus({ core: { running: true, paused: true } }).key, 'paused');
assert.equal(assistantHealthStatus({ core: { running: true, background: { running: true, lifecycle: 'recovering' } } }).label, 'CATCHING UP');
assert.equal(assistantHealthStatus({ core: { running: true, jobs: { queued: 2, overdue: 1 } } }).detail, 'The assistant is working through delayed background work.');
assert.equal(assistantHealthStatus({ core: { running: false, background: { running: false, lifecycle: 'unavailable' } } }).key, 'unavailable');
assert.equal(assistantHealthStatus({ core: { running: true, jobs: { queued: 3 } } }).detail, '3 durable jobs queued.');
assert.throws(() => new MobileCoreClient({ baseUrl: 'http://192.168.1.20:4747', token: 'secret', fetchImpl: async () => ({}) }), /require HTTPS/);
assert.throws(() => new MobileCoreClient({ baseUrl: 'https://user:pass@assistant.example', token: 'secret', fetchImpl: async () => ({}) }), /without embedded credentials/);

(async () => {
  const values = new Map();
  const storage = { getItem: async (key) => values.get(key) || null, setItem: async (key, value) => values.set(key, value) };
  let online = false; const calls = [];
  const fetchImpl = async (url, options) => {
    calls.push({ url, options });
    if (!online) throw new Error('offline');
    return { ok: true, status: 200, json: async () => (url.includes('/notifications') ? { notifications: [], nextCursor: 'cursor-1' } : { accepted: true }) };
  };
  const client = new MobileCoreClient({ baseUrl: 'http://127.0.0.1:4747', token: 'secret', fetchImpl, storage, clock: () => 100 });
  const queued = await client.sendMessage('remember this', { externalId: 'command-1' });
  assert.deepEqual(queued, { queued: true, commandId: 'command-1', pending: 1 });
  assert.equal(JSON.parse(values.get('signal-box.mobile.outbox.v1')).length, 1);
  online = true;
  const flushed = await client.flushOutbox();
  assert.deepEqual(flushed, { flushed: 1, pending: 0 });
  assert.equal(calls.at(-1).options.headers['Idempotency-Key'], 'command-1');
  assert.equal(JSON.parse(values.get('signal-box.mobile.outbox.v1')).length, 0);
  const synced = await client.syncNotifications();
  assert.equal(synced.nextCursor, 'cursor-1');
  assert.equal(values.get(NOTIFICATION_CURSOR_KEY), 'cursor-1');
  const pause = await client.setAssistantPaused(true);
  assert.equal(calls.at(-1).url, 'http://127.0.0.1:4747/api/v1/mobile/assistant/pause');
  assert.deepEqual(JSON.parse(calls.at(-1).options.body), { paused: true });
  assert.equal(pause.accepted, true);
  const runs = await client.autonomousRuns(3);
  assert.equal(calls.at(-1).url, 'http://127.0.0.1:4747/api/v1/mobile/assistant/autonomous-runs?limit=3');
  assert.deepEqual(runs, { accepted: true });
  const graph = await client.taskGraph({ depth: 1, limit: 10 });
  assert.equal(calls.at(-1).url, 'http://127.0.0.1:4747/api/v1/mobile/graph?taskId=&depth=1&limit=10');
  assert.deepEqual(graph, { accepted: true });
  const arrival = await client.setTaskContextTrigger('task-1', { placeKey: 'home' });
  assert.equal(calls.at(-1).url, 'http://127.0.0.1:4747/api/v1/mobile/tasks/task-1/context-trigger');
  assert.deepEqual(JSON.parse(calls.at(-1).options.body), { placeKey: 'home' });
  assert.equal(arrival.accepted, true);
  const confirmed = await client.confirmAutonomousRun('run-1', 'Verified provider confirmation.');
  assert.equal(calls.at(-1).url, 'http://127.0.0.1:4747/api/v1/mobile/assistant/autonomous-runs/run-1/confirm');
  assert.deepEqual(JSON.parse(calls.at(-1).options.body), { evidence: 'Verified provider confirmation.' });
  assert.equal(confirmed.accepted, true);
  const location = await client.sendLocation({ latitude: 40, longitude: -73, accuracy: 10, consent: true });
  const locationBody = JSON.parse(calls.at(-1).options.body);
  assert.equal(calls.at(-1).options.headers['Idempotency-Key'], locationBody.eventId);
  assert.equal(typeof locationBody.eventId, 'string');
  assert.equal(location.accepted, true);
  const sensor = await client.sendSensor({ sensor: 'battery', value: { level: 0.5 }, consent: true });
  const sensorBody = JSON.parse(calls.at(-1).options.body);
  assert.equal(calls.at(-1).options.headers['Idempotency-Key'], sensorBody.eventId);
  assert.equal(sensor.accepted, true);
  console.log('mobile client tests passed');
})().catch((error) => { console.error(error); process.exitCode = 1; });
