const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { EntityVault, PrivacyGateway } = require('../host/privacy/gateway');
const { candidateFromObservation } = require('../host/tasks/extract');

 (async () => {
const vault = new EntityVault();
const gateway = new PrivacyGateway({ vault });
const first = gateway.pseudonymize('Email me@example.com or call +1 (555) 123-4567.');
const second = gateway.pseudonymize('Reply to me@example.com.');
assert.match(first.text, /\[email:ent_[a-f0-9]+\]/);
assert.match(first.text, /\[phone:ent_[a-f0-9]+\]/);
assert.match(second.text, /\[email:ent_[a-f0-9]+\]/);
assert.equal(first.offsets[0].sourceStart, 6);
assert.equal(vault.rehydrate(first.offsets[0].entityId, 'email'), 'me@example.com');
assert.throws(() => vault.rehydrate(first.offsets[0].entityId, 'phone'), /mismatched/);
const nested = new PrivacyGateway({ vault: new EntityVault() }).prepareRemotePayload({ profile: { email: 'nested@example.com', notes: ['Call me at +1 555 555 5555'] } });
assert.doesNotMatch(JSON.stringify(nested), /nested@example.com|555 555 5555/);
assert.equal(await gateway.infer({ body: 'me@example.com' }), null);
const vaultDirectory = fs.mkdtempSync(path.join(os.tmpdir(), 'signal-box-vault-'));
const vaultFile = path.join(vaultDirectory, 'vault.json');
const persistent = new EntityVault({ filename: vaultFile, key: Buffer.alloc(32, 7) });
const stableId = persistent.idFor('email', 'stable@example.com');
assert.doesNotMatch(fs.readFileSync(vaultFile, 'utf8'), /stable@example.com/);
const reopened = new EntityVault({ filename: vaultFile, key: Buffer.alloc(32, 7) });
assert.equal(reopened.idFor('email', 'stable@example.com'), stableId);
assert.equal(reopened.rehydrate(stableId, 'email'), 'stable@example.com');
assert.throws(() => new EntityVault({ filename: vaultFile, key: Buffer.alloc(32, 8) }), /encrypted entity vault/);
assert.match(gateway.pseudonymize('Pay 4111 1111 1111 1111 at https://example.com/account').text, /\[card:ent_[a-f0-9]+\]/);
const recognized = await gateway.pseudonymizeWithRecognizer('Meet Priya at Acme Labs.', async () => [{ type: 'person', value: 'Priya', start: 5, end: 10 }, { type: 'organization', value: 'Acme Labs', start: 14, end: 23 }]);
assert.match(recognized.text, /\[person:ent_[a-f0-9]+\]/);
assert.match(recognized.text, /\[organization:ent_[a-f0-9]+\]/);
fs.rmSync(vaultDirectory, { recursive: true, force: true });

const observation = { observationId: 'obs-1', threadId: 'thread-1', subject: 'Friday handoff', body: "I'll send the handoff by Friday.", direction: 'outgoing' };
const candidate = candidateFromObservation(observation, { filters: { eligible: true } });
assert.equal(candidate.owner, 'self');
assert.equal(candidate.blocker, 'counterparty');
assert.equal(candidate.dueDate, 'friday');
assert.equal(candidate.evidence.text.includes('by Friday'), true);
console.log('privacy and task tests passed');
})().catch((error) => { console.error(error); process.exitCode = 1; });
