const assert = require('node:assert/strict');
const { SqliteStore } = require('../host/store/sqlite-store');

const store = new SqliteStore();
const add = (id, summary) => store.saveTaskCandidate({ candidateId: id, observationId: `obs-${id}`, summary, evidence: { start: 0, end: 1, text: summary }, extractorVersion: 'test' });
add('task-a', 'Prepare proposal');
add('task-b', 'Get pricing');
add('task-c', 'Confirm budget');
const beforeRelationWake = store.exportData().data.jobs.filter((job) => job.kind === 'assistant.proactive-actions' && JSON.parse(job.payload_json).taskId === 'task-a').length;
store.addTaskRelation('task-a', 'task-b', 'depends_on', { reason: 'pricing is required' });
const afterRelationWake = store.exportData().data.jobs.filter((job) => job.kind === 'assistant.proactive-actions' && JSON.parse(job.payload_json).taskId === 'task-a').length;
assert.equal(afterRelationWake, beforeRelationWake + 1, 'adding a dependency wakes the dependent task');
store.addTaskRelation('task-a', 'task-b', 'waiting_on', { reason: 'awaiting pricing' });
store.addTaskRelation('task-b', 'task-c', 'depends_on', { reason: 'budget is required' });
const beforeDependencyWake = store.exportData().data.jobs.filter((job) => job.kind === 'assistant.proactive-actions' && JSON.parse(job.payload_json).taskId === 'task-a').length;
store.setTaskStatus('task-b', 'done', { source: 'test' });
const afterDependencyWake = store.exportData().data.jobs.filter((job) => job.kind === 'assistant.proactive-actions' && JSON.parse(job.payload_json).taskId === 'task-a').length;
assert.equal(afterDependencyWake, beforeDependencyWake + 1, 'dependency completion wakes the blocked task');
store.upsertContext({ recordType: 'project', recordKey: 'launch', value: { name: 'Launch' }, source: { channel: 'test' }, confidence: 'high', confirmed: true });
store.correctTask('task-a', { project: 'launch' });
assert.deepEqual(store.taskRelations('task-a')[0].details, { reason: 'pricing is required' });
assert.throws(() => store.addTaskRelation('task-b', 'task-a', 'depends_on'), /cycle/);
const graph = store.taskGraph();
assert.ok(graph.edges.some((edge) => edge.type === 'depends_on' && edge.from === 'task:task-a' && edge.to === 'task:task-b'));
assert.ok(graph.edges.some((edge) => edge.type === 'waiting_on' && edge.from === 'task:task-a' && edge.to === 'task:task-b'));
assert.ok(graph.nodes.some((node) => node.id === 'context:project:launch' && node.type === 'context'));
assert.ok(graph.edges.some((edge) => edge.type === 'context' && edge.from === 'task:task-a' && edge.to === 'context:project:launch'));
const bounded = store.taskGraph({ taskId: 'task-a', depth: 1, limit: 10 });
assert.deepEqual(bounded.nodes.filter((node) => node.type === 'task').map((node) => node.id).sort(), ['task:task-a', 'task:task-b']);
assert.equal(store.taskGraph({ taskId: 'task-a', depth: 2 }).nodes.filter((node) => node.type === 'task').length, 3);
assert.throws(() => store.addTaskRelation('task-a', 'missing', 'depends_on'), /Both related tasks/);
assert.ok(store.exportData().data.task_relations.length === 3);
store.close();
console.log('task relation tests passed');
