const assert = require('node:assert/strict');
const { SqliteStore } = require('../host/store/sqlite-store');
const { TaskService } = require('../host/tasks/service');

const store = new SqliteStore();
store.saveObservation({ observationId: 'o1', messageId: 'm1', threadId: 't1', subject: 'Friday handoff', body: "I'll send the handoff by Friday.", direction: 'outgoing', to: ['client@example.com'] }, 'fake');
const service = new TaskService({ store });
const first = service.processAll('fake');
assert.equal(first.length, 1);
assert.equal(first[0].status, 'active');
const taskId = first[0].taskId;
assert.equal(service.processAll('fake')[0].preserved, true);
assert.equal(store.correctTask(taskId, { summary: 'Corrected handoff' }).summary, 'Corrected handoff');
store.setTaskStatus(taskId, 'dismissed', { reason: 'not useful' });
assert.equal(store.listTasks().length, 0);
assert.equal(store.listTasks({ includeDismissed: true })[0].status, 'dismissed');
store.saveObservation({ observationId: 'o-snooze', messageId: 'm-snooze', threadId: 't-snooze', subject: 'Snoozed', body: "I'll send this by Friday.", direction: 'outgoing', to: ['client@example.com'] }, 'fake');
const snoozed = service.processAll('fake').find((task) => task.summary === 'Snoozed');
store.snoozeTask(snoozed.taskId, Date.now() + 60_000);
assert.equal(store.listTasks().find((task) => task.taskId === snoozed.taskId).status, 'snoozed');
store.setSuppression('counterparty', 'client@example.com');
assert.equal(store.isSuppressed('counterparty', 'client@example.com'), true);
store.saveObservation({ observationId: 'o2', messageId: 'm2', threadId: 't1', subject: 'Friday handoff', body: "I'll send the handoff by Friday.", direction: 'outgoing' }, 'fake');
assert.equal(service.processAll('fake').length, 3, 'new evidence is tracked without changing the dismissed task');
assert.equal(service.processObservations([{ observationId: 'removed', removed: true }]).length, 0);
assert.equal(store.listTasks({ includeDismissed: true }).filter((task) => task.status === 'dismissed').length, 1);
const exported = store.exportData();
assert.equal(exported.formatVersion, 1);
assert.equal(exported.data.observations.length, 3);
store.saveObservation({ observationId: 'gmail-delete', messageId: 'gmail-delete', threadId: 'gmail-delete', subject: 'Stored Gmail', body: 'A message.', direction: 'incoming' }, 'gmail:test@example.com');
const deleted = store.deleteMailData();
assert.equal(deleted.observations, 1);
assert.equal(store.observations('fake').length, 3, 'non-Gmail adapters remain available');
const multi = { observationId: 'multi', messageId: 'multi', threadId: 'multi-thread', subject: 'Launch plan', body: "I'll send the contract by Friday, and I'll schedule the review by Monday.", direction: 'outgoing', to: ['client@example.com'] };
store.saveObservation(multi, 'fake');
const extracted = service.processObservation(multi);
assert.equal(extracted.length, 2, 'separate commitments in one message remain separate tasks');
assert.notEqual(extracted[0].obligationKey, extracted[1].obligationKey);
const multiText = `${multi.subject}\n${multi.body}`;
for (const task of extracted) assert.equal(multiText.slice(task.evidence.start, task.evidence.end), task.evidence.text, 'task evidence span maps to source text');
const conjunction = { observationId: 'multi-conjunction', messageId: 'multi-conjunction', threadId: 'multi-conjunction-thread', subject: 'Launch plan', body: "I'll send the contract and I'll review the plan.", direction: 'outgoing', provider: 'gmail', to: ['client@example.com'] };
const conjunctionTasks = service.processObservation(conjunction);
assert.equal(conjunctionTasks.length, 2, 'conjoined commitments remain separate when punctuation is absent');
assert.notEqual(conjunctionTasks[0].obligationKey, conjunctionTasks[1].obligationKey);
const conjunctionText = `${conjunction.subject}\n${conjunction.body}`;
for (const task of conjunctionTasks) assert.equal(conjunctionText.slice(task.evidence.start, task.evidence.end), task.evidence.text, 'conjoined evidence span maps to source text');
store.saveObservation({ observationId: 'orphan-observation', messageId: 'orphan-message', threadId: 'orphan-thread', subject: 'Orphan', body: "I'll finish this by Friday.", direction: 'outgoing' }, 'fake');
const orphan = service.processAll('fake').find((task) => task.taskId === 'orphan-observation:local-1');
assert.equal(store.removeObservation('fake', 'orphan-message'), true);
assert.equal(store.listTasks({ includeDismissed: true }).find((task) => task.taskId === orphan.taskId).sourceUnavailable, true);
assert.equal(service.processObservation(store.observations('fake').find((item) => item.messageId === 'orphan-message')).length, 0);
store.close();
console.log('task store tests passed');
